package bluerock

import "github.com/cbaguilar/svwatergo/internal/systemservice/schema"

var TableDef = schema.TableDef{
	Columns: []schema.ColumnDef{
		{Name: "id", SQLiteType: "INTEGER PRIMARY KEY", PostgresType: "BIGSERIAL PRIMARY KEY"},
		{Name: "location", SQLiteType: "TEXT", PostgresType: "TEXT", NotNull: true},
		{Name: "totalroflow", SQLiteType: "INTEGER", PostgresType: "BIGINT"},
		{Name: "totalfeedflow", SQLiteType: "INTEGER", PostgresType: "BIGINT"},
		{Name: "totalrecycleflow", SQLiteType: "INTEGER", PostgresType: "BIGINT"},
		{Name: "totaldelflow", SQLiteType: "INTEGER", PostgresType: "BIGINT"},
		{Name: "dumpproduct", SQLiteType: "INTEGER", PostgresType: "BOOLEAN"},
		{Name: "wellpumprun", SQLiteType: "INTEGER", PostgresType: "BOOLEAN"},
		{Name: "wellpumpauto", SQLiteType: "INTEGER", PostgresType: "BOOLEAN"},
		{Name: "feedpumprun", SQLiteType: "INTEGER", PostgresType: "BOOLEAN"},
		{Name: "ropumprun", SQLiteType: "INTEGER", PostgresType: "BOOLEAN"},
		{Name: "deliveryrun", SQLiteType: "INTEGER", PostgresType: "BOOLEAN"},
		{Name: "deliveryauto", SQLiteType: "INTEGER", PostgresType: "BOOLEAN"},
		{Name: "inletrun", SQLiteType: "INTEGER", PostgresType: "BOOLEAN"},
		{Name: "concbypassrun", SQLiteType: "INTEGER", PostgresType: "BOOLEAN"},
		{Name: "proddiversionrun", SQLiteType: "INTEGER", PostgresType: "BOOLEAN"},
		{Name: "plctime", SQLiteType: "TEXT", PostgresType: "TIMESTAMPTZ", NotNull: true},
		{Name: "permeateflow", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "deliveryflow", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "feedflow", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "concentrateflow", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "recycleflow", SQLiteType: "INTEGER", PostgresType: "BIGINT"},
		{Name: "feedtanklevel", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "dailypermflow", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "alarm", SQLiteType: "INTEGER", PostgresType: "BOOLEAN"},
		{Name: "alarmword", SQLiteType: "INTEGER", PostgresType: "BIGINT"},
		{Name: "rostandby", SQLiteType: "INTEGER", PostgresType: "BOOLEAN"},
		{Name: "state", SQLiteType: "INTEGER", PostgresType: "BIGINT"},
		{Name: "lockout", SQLiteType: "INTEGER", PostgresType: "BOOLEAN"},
		{Name: "runflush", SQLiteType: "INTEGER", PostgresType: "BOOLEAN"},
		{Name: "warnword0", SQLiteType: "INTEGER", PostgresType: "BIGINT"},
		{Name: "warnword1", SQLiteType: "INTEGER", PostgresType: "BIGINT"},
		{Name: "totalhrs", SQLiteType: "INTEGER", PostgresType: "BIGINT"},
		{Name: "permtds", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "feedtds", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "permnitrate", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "permtemp", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "prodtanklevel", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "prodtankdisable", SQLiteType: "INTEGER", PostgresType: "BOOLEAN"},
		{Name: "prodtankdepth", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "feedtankdepth", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "residualtankdepth", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "inletpressure", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "concentratepressure", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "permeatepressure", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "ropressure", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "deliverypressure", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "feedpressure", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "recyclevalveposition", SQLiteType: "INTEGER", PostgresType: "BIGINT"},
		{Name: "ropressctrlvalveposition", SQLiteType: "INTEGER", PostgresType: "BIGINT"},
		{Name: "ropumpspeed", SQLiteType: "INTEGER", PostgresType: "BIGINT"},
		{Name: "powermeter", SQLiteType: "INTEGER", PostgresType: "BIGINT"},
		{Name: "flushduret", SQLiteType: "INTEGER", PostgresType: "BIGINT"},
		{Name: "producttds", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "chlorinepumprun", SQLiteType: "INTEGER", PostgresType: "BOOLEAN"},
		{Name: "residtankvalverun", SQLiteType: "INTEGER", PostgresType: "BOOLEAN"},
		{Name: "residualtanklevel", SQLiteType: "REAL", PostgresType: "DOUBLE PRECISION"},
		{Name: "recordtime", SQLiteType: "TEXT", PostgresType: "TIMESTAMPTZ", NotNull: true},
		{Name: "flushrun", SQLiteType: "INTEGER", PostgresType: "BOOLEAN"},
	},
	Unique: []string{"location", "plctime"},
}
