site: bluerock
display_name: Bluerock
formal_name: Blue Rock Water System
alert_street_addr: 16 Market Circle
state_water_system_id: "2701229"
alert_contact_names: Market Circle Partners, Rick Sagin and Babette Sagin, Blue Rock Water System Owners
alert_contact_phone: "+1 (831) 917-8380"
sensors:
  - key: plctime
    name: PLC Time
  - key: permeateflow
    name: Permeate Flow
    units: gpm
  - key: feedflow
    name: Feed Flow
    units: gpm
  - key: deliveryflow
    name: Delivery Flow
    units: gpm
  - key: permtds
    name: Permeate TDS
    units: uS

soft_sensors:
  - key: ro_recovery
    name: RO Recovery
    units: "%"
    note: "permeateflow / feedflow * 100"
