site: bluerock
sensors:
  - key: plctime
    name: PLC Time
  - key: permeateflow
    name: Permeate Flow
    units: gpm
  - key: feedflow
    name: Feed Flow
    units: gpm
  - key: deliveryflow
    name: Delivery Flow
    units: gpm
  - key: permtds
    name: Permeate TDS
    units: uS

soft_sensors:
  - key: ro_recovery
    name: RO Recovery
    units: "%"
    note: "permeateflow / feedflow * 100"
