site: santateresa
sensors:
  - key: plctime
    name: PLC Time
  - key: permeateflow
    name: Permeate Flow
    units: gpm
  - key: feedflow
    name: Feed Flow
    units: gpm
  - key: deliveryflow
    name: Delivery Flow
    units: gpm

soft_sensors:
  - key: feedflow_soft
    name: Feed Flow (Estimated)
    units: gpm
    note: "Estimated FTF = inletflow - recycleflow"
